/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springcorepractice;


import org.springframework.context.support.ClassPathXmlApplicationContext;
import springcorepractice.music.Music;

public class App {
    public static void main(String[] args) {
        ClassPathXmlApplicationContext applicationContext = new ClassPathXmlApplicationContext("applicationContext.xml");
        MusicPlayer musicPlayer = applicationContext.getBean("musicPlayer", MusicPlayer.class);
        musicPlayer.playMusic();
        applicationContext.close();
    }
}
